baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'SuperMinimalDemoSite'
copyright = '© Nobody. Just use this as you like.'

[markup.goldmark.renderer]
unsafe = true


[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'SuperMinimalCSS'
pageRef = '/superminimalcss'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
